import {
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

/**
 * Enums
 */
export const quoteStatusEnum = pgEnum('quote_status', ['pending', 'used', 'expired']);
export const paymentStatusEnum = pgEnum('payment_status', ['pending', 'settled', 'failed']);
export const apiKeyPlanEnum = pgEnum('api_key_plan', ['free', 'pro', 'enterprise']);
export const lightningInvoiceStatusEnum = pgEnum('lightning_invoice_status', [
  'pending',
  'paid',
  'expired',
]);

/**
 * quotes — stores DEX swap quotes generated by the core quote engine (packages/core/src/quote.ts).
 */
export const quotes = pgTable(
  'quotes',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    endpointUrl: text('endpoint_url').notNull(),
    inputToken: varchar('input_token', { length: 32 }).notNull(),
    inputTokenAddress: varchar('input_token_address', { length: 66 }),
    inputChainId: integer('input_chain_id').notNull(),
    inputAmount: varchar('input_amount', { length: 78 }).notNull(),
    usdcRequired: varchar('usdc_required', { length: 78 }).notNull(),
    usdcOnChain: varchar('usdc_on_chain', { length: 78 }),
    feeBps: integer('fee_bps').notNull().default(20),
    routeData: jsonb('route_data'),
    status: quoteStatusEnum('status').notNull().default('pending'),
  },
  (table) => [
    index('quotes_status_idx').on(table.status),
    index('quotes_expires_at_idx').on(table.expiresAt),
  ],
);

/**
 * payments — stores completed (or attempted) payment records, one per settled x402 payment.
 */
export const payments = pgTable(
  'payments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    quoteId: uuid('quote_id').references(() => quotes.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    txHash: varchar('tx_hash', { length: 66 }),
    blockNumber: numeric('block_number', { precision: 20, scale: 0 }),
    fromAddress: varchar('from_address', { length: 42 }),
    toAddress: varchar('to_address', { length: 42 }),
    inputToken: varchar('input_token', { length: 32 }).notNull(),
    inputAmount: varchar('input_amount', { length: 78 }).notNull(),
    usdcAmount: varchar('usdc_amount', { length: 78 }).notNull(),
    feeUsdc: varchar('fee_usdc', { length: 78 }).notNull(),
    apiEndpoint: text('api_endpoint').notNull(),
    facilitatorUrl: text('facilitator_url'),
    xPaymentResponse: text('x_payment_response'),
    status: paymentStatusEnum('status').notNull().default('pending'),
  },
  (table) => [
    index('payments_status_idx').on(table.status),
    index('payments_quote_id_idx').on(table.quoteId),
    index('payments_tx_hash_idx').on(table.txHash),
  ],
);

/**
 * api_keys — developer API keys. Only the SHA-256 hash of the key is ever stored.
 */
export const apiKeys = pgTable(
  'api_keys',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    keyHash: text('key_hash').notNull(),
    name: varchar('name', { length: 128 }).notNull(),
    ownerEmail: varchar('owner_email', { length: 256 }),
    plan: apiKeyPlanEnum('plan').notNull().default('free'),
    monthlyLimitUsd: numeric('monthly_limit_usd', { precision: 20, scale: 2 })
      .notNull()
      .default('100'),
    currentMonthVolumeUsd: numeric('current_month_volume_usd', { precision: 20, scale: 2 })
      .notNull()
      .default('0'),
    isActive: boolean('is_active').notNull().default(true),
  },
  (table) => [index('api_keys_key_hash_idx').on(table.keyHash)],
);

/**
 * lightning_invoices — Lightning Network invoice tracking (Phase 3/4 stub in Phase 1).
 */
export const lightningInvoices = pgTable(
  'lightning_invoices',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    bolt11: text('bolt11').notNull(),
    paymentHash: varchar('payment_hash', { length: 64 }).notNull(),
    amountSats: numeric('amount_sats', { precision: 20, scale: 0 }).notNull(),
    usdcEquivalent: varchar('usdc_equivalent', { length: 78 }).notNull(),
    apiEndpoint: text('api_endpoint').notNull(),
    status: lightningInvoiceStatusEnum('status').notNull().default('pending'),
  },
  (table) => [
    index('lightning_invoices_payment_hash_idx').on(table.paymentHash),
    index('lightning_invoices_status_idx').on(table.status),
  ],
);

export type Quote = typeof quotes.$inferSelect;
export type NewQuote = typeof quotes.$inferInsert;
export type Payment = typeof payments.$inferSelect;
export type NewPayment = typeof payments.$inferInsert;
export type ApiKey = typeof apiKeys.$inferSelect;
export type NewApiKey = typeof apiKeys.$inferInsert;
export type LightningInvoice = typeof lightningInvoices.$inferSelect;
export type NewLightningInvoice = typeof lightningInvoices.$inferInsert;
