import type {
  ConfigEnvironment,
  ConfigGroup,
  ConfigGroupMeta,
  ConfigKeyDefinition,
  FeatureName,
  RequirementRule,
} from './types.ts';
import { exactHexLength, numberRange, oneOfProtocols } from './validators.ts';

const ALL: ConfigKeyDefinition['required'] = { dev: true, staging: true, production: true };
const FROM_STAGING: ConfigKeyDefinition['required'] = {
  dev: false,
  staging: true,
  production: true,
};
const PRODUCTION_ONLY: ConfigKeyDefinition['required'] = {
  dev: false,
  staging: false,
  production: true,
};
const OPTIONAL: ConfigKeyDefinition['required'] = { dev: false, staging: false, production: false };

export const CONFIG_GROUPS: readonly ConfigGroupMeta[] = [
  {
    group: 'runtime',
    title: 'Runtime',
    summary: 'Which environment profile AnyX validates against and how loudly it logs.',
  },
  {
    group: 'network',
    title: 'Network / RPC',
    summary: 'JSON-RPC endpoints for every chain AnyX reads from or settles on.',
  },
  {
    group: 'dex',
    title: 'DEX aggregators and pricing',
    summary: 'Quote sources for the swap engine, plus slippage and routing preferences.',
  },
  {
    group: 'x402',
    title: 'x402 facilitators',
    summary: 'Primary and fallback facilitators that verify and settle EIP-3009 authorizations.',
  },
  {
    group: 'signer',
    title: 'Signer / key management',
    summary: 'How EIP-3009 authorizations are signed: a local hot key, or Turnkey / Lit MPC.',
  },
  {
    group: 'fees',
    title: 'Fees and spreads',
    summary: 'The revenue model: base spread, per-asset-class spreads, and floors.',
  },
  {
    group: 'storage',
    title: 'Storage',
    summary: 'PostgreSQL for receipts and quotes, Redis for quote caching and rate limits.',
  },
  {
    group: 'api',
    title: 'API server',
    summary: 'Ports, CORS, admin authentication, and per-tier rate limits for the Hono API.',
  },
  {
    group: 'contracts',
    title: 'Contract addresses',
    summary: 'Deployed AnyX contracts plus the fixed third-party addresses they depend on.',
  },
  {
    group: 'bridge',
    title: 'Cross-chain bridge and float',
    summary: 'Circle CCTP, Stargate, and the USDC float pool that fronts cross-chain payments.',
  },
  {
    group: 'lightning',
    title: 'Lightning Network',
    summary: 'LND connection details for the Bitcoin Lightning payment path.',
  },
  {
    group: 'billing',
    title: 'Billing (Stripe)',
    summary: 'Stripe subscription billing for the Pro tier of the hosted API.',
  },
  {
    group: 'deploy',
    title: 'Deployment and release',
    summary: 'Fly.io deploy targets, health checks, and npm publishing.',
  },
  {
    group: 'orchestrator',
    title: 'Multi-agent orchestrator',
    summary: 'How the build orchestrator dispatches specialist agents and gates production.',
  },
];

export const FEATURE_DESCRIPTIONS: Readonly<Record<FeatureName, string>> = {
  evmQuotes: 'Quote and route EVM tokens to USDC through a DEX aggregator',
  solanaQuotes: 'Quote and route SOL / SPL tokens to USDC on Solana via Jupiter',
  priceOracle: 'Authenticated CoinGecko pricing for token valuation and BTC/USD rates',
  onchainSwap: 'Atomic on-chain swap-and-pay through the deployed AnyXRouter contract',
  floatSettlement: 'Settle from a pre-funded USDC float instead of an on-chain swap',
  persistence: 'Persist quotes, payments, receipts, and API keys',
  quoteCache: 'Cache DEX quotes and enforce quote freshness windows',
  rateLimiting: 'Per-API-key rate limiting and monthly volume accounting',
  adminApi: 'Administrative endpoints (key issuance, partner settlement)',
  localSigner: 'Sign EIP-3009 authorizations with a local hot key',
  mpcSigner: 'Sign EIP-3009 authorizations through Turnkey or Lit Protocol MPC',
  cdpFacilitator: 'Authenticated settlement through the Coinbase CDP facilitator',
  facilitatorFailover: 'Automatic failover to a secondary x402 facilitator',
  crosschainCctp: 'Circle CCTP bridging of USDC between supported chains',
  stargateBridge: 'Stargate bridging as a CCTP fallback for USDT and ETH',
  reserveFloat: 'Reserve pool accounting and float replenishment',
  lightning: 'Bitcoin Lightning invoices settling x402 payments',
  stripeBilling: 'Stripe checkout, webhooks, and Pro-tier subscription management',
  testnetDeploys: 'Contract deploys and integration runs against Base Sepolia',
  contractVerification: 'Automatic contract verification on Basescan',
  apiDeploy: 'Automated API deployment to Fly.io from CI',
  sdkPublish: 'Automated npm publishing of @anyx/sdk and integration packages',
  orchestratorRemoteExecutor: 'Dispatch agent tasks to a remote executor endpoint',
  orchestratorProductionAutoApprove:
    'Allow the orchestrator to promote to production without a human approval',
};

function def(definition: ConfigKeyDefinition): ConfigKeyDefinition {
  return definition;
}

export const CONFIG_REGISTRY: readonly ConfigKeyDefinition[] = [
  // ---------------------------------------------------------------- runtime
  def({
    key: 'ANYX_ENV',
    group: 'runtime',
    configPath: 'runtime.env',
    type: 'enum',
    enumValues: ['dev', 'staging', 'production'],
    required: OPTIONAL,
    secret: false,
    default: 'dev',
    description:
      'Which environment profile to validate against. Controls which keys are treated as required.',
    example: 'dev',
    howToObtain: 'Choose one of dev, staging, or production. No third party involved.',
    blocksFeatures: [],
  }),
  def({
    key: 'LOG_LEVEL',
    group: 'runtime',
    configPath: 'runtime.logLevel',
    type: 'enum',
    enumValues: ['debug', 'info', 'warn', 'error'],
    required: OPTIONAL,
    secret: false,
    default: 'info',
    description: 'Minimum severity written to stdout by the API, orchestrator, and scripts.',
    example: 'info',
    howToObtain: 'Choose one of debug, info, warn, or error. No third party involved.',
    blocksFeatures: [],
  }),

  // ---------------------------------------------------------------- network
  def({
    key: 'RPC_URL_BASE',
    group: 'network',
    configPath: 'network.rpcUrlBase',
    type: 'url',
    required: ALL,
    secret: false,
    default: 'https://mainnet.base.org',
    description: 'Base mainnet JSON-RPC endpoint. Every settlement read and write goes through it.',
    example: 'https://mainnet.base.org',
    howToObtain:
      'The public endpoint https://mainnet.base.org works for development but is rate limited. For staging and production create a project at https://dashboard.alchemy.com (or https://www.quicknode.com), add a Base Mainnet app, and copy its HTTPS URL.',
    docsUrl: 'https://docs.base.org/network-information',
    blocksFeatures: ['evmQuotes', 'onchainSwap', 'floatSettlement'],
    validate: oneOfProtocols('http', 'https'),
  }),
  def({
    key: 'RPC_URL_ETHEREUM',
    group: 'network',
    configPath: 'network.rpcUrlEthereum',
    type: 'url',
    required: OPTIONAL,
    secret: false,
    default: 'https://eth.llamarpc.com',
    description:
      'Ethereum mainnet JSON-RPC endpoint, used for WBTC/USDT-on-Ethereum routing and CCTP.',
    example: 'https://eth.llamarpc.com',
    howToObtain:
      'Use the public https://eth.llamarpc.com endpoint for development, or create an Ethereum Mainnet app at https://dashboard.alchemy.com and copy its HTTPS URL.',
    blocksFeatures: ['crosschainCctp'],
    validate: oneOfProtocols('http', 'https'),
  }),
  def({
    key: 'RPC_URL_BASE_SEPOLIA',
    group: 'network',
    configPath: 'network.rpcUrlBaseSepolia',
    type: 'url',
    required: FROM_STAGING,
    secret: false,
    default: 'https://sepolia.base.org',
    description:
      'Base Sepolia testnet endpoint used for contract deploys and staging integration runs.',
    example: 'https://sepolia.base.org',
    howToObtain:
      'The public endpoint https://sepolia.base.org is sufficient. Fund the deployer with testnet ETH from https://www.coinbase.com/faucets/base-ethereum-sepolia-faucet.',
    docsUrl: 'https://docs.base.org/network-information',
    blocksFeatures: ['testnetDeploys'],
    validate: oneOfProtocols('http', 'https'),
  }),
  def({
    key: 'RPC_URL_SOLANA',
    group: 'network',
    configPath: 'network.rpcUrlSolana',
    type: 'url',
    required: OPTIONAL,
    secret: false,
    default: 'https://api.mainnet-beta.solana.com',
    description: 'Solana JSON-RPC endpoint for Jupiter swap routing and CCTP burns on Solana.',
    example: 'https://api.mainnet-beta.solana.com',
    howToObtain:
      'The public endpoint https://api.mainnet-beta.solana.com works for low volume. For production create a Solana endpoint at https://www.helius.dev or https://triton.one and copy its HTTPS URL.',
    blocksFeatures: ['solanaQuotes'],
    validate: oneOfProtocols('http', 'https'),
  }),
  def({
    key: 'CHAIN_ID_DEFAULT',
    group: 'network',
    configPath: 'network.defaultChainId',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 8453,
    description: 'Chain that x402 settlement targets by default. 8453 is Base mainnet.',
    example: '8453',
    howToObtain: 'Use 8453 for Base mainnet or 84532 for Base Sepolia. No third party involved.',
    blocksFeatures: [],
  }),

  // -------------------------------------------------------------------- dex
  def({
    key: 'ONEINCH_API_KEY',
    group: 'dex',
    configPath: 'dex.oneInchApiKey',
    type: 'string',
    required: PRODUCTION_ONLY,
    secret: true,
    description:
      '1inch Developer Portal key. Primary quote and swap-calldata source for EVM chains.',
    example: '<your-1inch-portal-key>',
    howToObtain:
      "1. Sign in at https://portal.1inch.dev. 2. Create an application. 3. Enable the Swap API (and Fusion if you want intent-based routing). 4. Copy the API key from the application's Credentials tab. Free tier covers development; production volume needs a paid plan.",
    docsUrl: 'https://portal.1inch.dev/documentation',
    blocksFeatures: ['evmQuotes'],
  }),
  def({
    key: 'ZEROX_API_KEY',
    group: 'dex',
    configPath: 'dex.zeroExApiKey',
    type: 'string',
    required: PRODUCTION_ONLY,
    secret: true,
    description:
      '0x Swap API key. Fallback quote source when 1inch is unavailable or returns no route.',
    example: '<your-0x-dashboard-key>',
    howToObtain:
      '1. Create an account at https://dashboard.0x.org. 2. Create a project. 3. Copy the API key. 4. Send it as the `0x-api-key` header. The free tier is rate limited per month.',
    docsUrl: 'https://0x.org/docs/api',
    blocksFeatures: ['evmQuotes'],
  }),
  def({
    key: 'JUPITER_API_URL',
    group: 'dex',
    configPath: 'dex.jupiterApiUrl',
    type: 'url',
    required: OPTIONAL,
    secret: false,
    default: 'https://quote-api.jup.ag/v6',
    description: 'Jupiter aggregator base URL used for SOL and SPL token routing on Solana.',
    example: 'https://quote-api.jup.ag/v6',
    howToObtain:
      'The public endpoint requires no key. For higher rate limits request a hosted endpoint at https://station.jup.ag/docs/apis/self-hosted and put its URL here.',
    docsUrl: 'https://station.jup.ag/docs/apis/swap-api',
    blocksFeatures: ['solanaQuotes'],
    validate: oneOfProtocols('http', 'https'),
  }),
  def({
    key: 'COINGECKO_API_KEY',
    group: 'dex',
    configPath: 'dex.coingeckoApiKey',
    type: 'string',
    required: OPTIONAL,
    secret: true,
    description:
      'CoinGecko Demo or Pro key for USD pricing and the BTC/USD rate used to size Lightning invoices.',
    example: '<your-coingecko-demo-key>',
    howToObtain:
      'Optional. Without a key AnyX uses the public CoinGecko endpoint, which is heavily rate limited. For a key: 1. Create an account at https://www.coingecko.com/en/developers/dashboard. 2. Generate a Demo (free) or Pro key. 3. Paste it here.',
    docsUrl: 'https://docs.coingecko.com/reference/introduction',
    blocksFeatures: ['priceOracle'],
  }),
  def({
    key: 'DEFAULT_SLIPPAGE_BPS',
    group: 'dex',
    configPath: 'dex.defaultSlippageBps',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 50,
    description:
      'Default slippage tolerance in basis points when a caller does not specify one. 50 = 0.5%.',
    example: '50',
    howToObtain: 'A policy decision, not a credential. 50 bps matches the PRD default.',
    blocksFeatures: [],
    validate: numberRange(1, 1000),
  }),
  def({
    key: 'DEX_PRIORITY',
    group: 'dex',
    configPath: 'dex.priority',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    default: '1inch,0x',
    description:
      'Comma-separated aggregator preference order. The first healthy source that returns a route wins.',
    example: '1inch,0x',
    howToObtain: 'A policy decision. Valid entries: 1inch, 0x, jupiter.',
    blocksFeatures: [],
  }),
  def({
    key: 'QUOTE_TIMEOUT_MS',
    group: 'dex',
    configPath: 'dex.quoteTimeoutMs',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 2500,
    description:
      'Per-aggregator quote timeout. Exceeding it drops that source from the current comparison.',
    example: '2500',
    howToObtain: 'A tuning decision, not a credential.',
    blocksFeatures: [],
    validate: numberRange(250, 30000),
  }),

  // ------------------------------------------------------------------- x402
  def({
    key: 'FACILITATOR_URL',
    group: 'x402',
    configPath: 'x402.facilitatorUrl',
    type: 'url',
    required: ALL,
    secret: false,
    default: 'https://api.cdp.coinbase.com/platform/v2/x402',
    description:
      'Primary x402 facilitator that verifies signatures and submits transferWithAuthorization.',
    example: 'https://api.cdp.coinbase.com/platform/v2/x402',
    howToObtain:
      'The Coinbase CDP facilitator URL above is the default. To self-host, deploy a facilitator (for example qntx/facilitator) and point this at your instance.',
    docsUrl: 'https://docs.cdp.coinbase.com/x402/docs/welcome',
    blocksFeatures: [],
    validate: oneOfProtocols('http', 'https'),
  }),
  def({
    key: 'FACILITATOR_FALLBACK_URL',
    group: 'x402',
    configPath: 'x402.facilitatorFallbackUrl',
    type: 'url',
    required: PRODUCTION_ONLY,
    secret: false,
    description: 'Secondary facilitator used when the primary is unhealthy or refuses to settle.',
    example: 'https://facilitator.your-domain.example/x402',
    howToObtain:
      'Deploy a second facilitator you control (qntx/facilitator, x402-sovereign, or OpenFacilitator) and paste its base URL. Without it, a facilitator outage or censorship event stops settlement.',
    blocksFeatures: ['facilitatorFailover'],
    validate: oneOfProtocols('http', 'https'),
  }),
  def({
    key: 'FACILITATOR_TIMEOUT_MS',
    group: 'x402',
    configPath: 'x402.facilitatorTimeoutMs',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 2000,
    description:
      'Health-check and request timeout before failing over to the fallback facilitator.',
    example: '2000',
    howToObtain: 'A tuning decision. The PRD requires failover within 2 seconds.',
    blocksFeatures: [],
    validate: numberRange(250, 30000),
  }),
  def({
    key: 'X402_MAX_TIMEOUT_SECONDS',
    group: 'x402',
    configPath: 'x402.maxTimeoutSeconds',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 300,
    description:
      'Upper bound AnyX honours for an authorization validity window, matching x402 maxTimeoutSeconds.',
    example: '300',
    howToObtain: 'A policy decision. 300 seconds matches typical x402 server challenges.',
    blocksFeatures: [],
    validate: numberRange(30, 3600),
  }),
  def({
    key: 'CDP_API_KEY_ID',
    group: 'x402',
    configPath: 'x402.cdpApiKeyId',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    description:
      'Coinbase Developer Platform API key id, required for authenticated CDP facilitator calls.',
    example: '<your-cdp-api-key-id>',
    howToObtain:
      '1. Sign in at https://portal.cdp.coinbase.com. 2. Open API Keys and create a Secret API key. 3. Copy the key id here and the private key into CDP_API_KEY_SECRET.',
    docsUrl: 'https://docs.cdp.coinbase.com/get-started/authentication',
    blocksFeatures: ['cdpFacilitator'],
  }),
  def({
    key: 'CDP_API_KEY_SECRET',
    group: 'x402',
    configPath: 'x402.cdpApiKeySecret',
    type: 'string',
    required: OPTIONAL,
    secret: true,
    description: 'Coinbase Developer Platform API private key paired with CDP_API_KEY_ID.',
    example: '<your-cdp-api-private-key>',
    howToObtain:
      'Shown exactly once when you create the Secret API key at https://portal.cdp.coinbase.com. Store it in your secret manager; if lost, rotate the key.',
    docsUrl: 'https://docs.cdp.coinbase.com/get-started/authentication',
    blocksFeatures: ['cdpFacilitator'],
  }),

  // ----------------------------------------------------------------- signer
  def({
    key: 'SIGNER_MODE',
    group: 'signer',
    configPath: 'signer.mode',
    type: 'enum',
    enumValues: ['local', 'turnkey', 'lit'],
    required: OPTIONAL,
    secret: false,
    default: 'local',
    description:
      'Which signing backend produces EIP-3009 authorizations. Production should not use `local`.',
    example: 'local',
    howToObtain:
      'Choose local for development. Choose turnkey or lit for production and fill in the matching credentials below.',
    blocksFeatures: [],
  }),
  def({
    key: 'PRIVATE_KEY',
    group: 'signer',
    configPath: 'signer.privateKey',
    type: 'hex',
    required: OPTIONAL,
    secret: true,
    description:
      'Hot signer private key used when SIGNER_MODE=local. Holds the USDC float and signs authorizations.',
    example: '0x<64-hex-characters>',
    howToObtain:
      'Generate a fresh key that is used for nothing else: `openssl rand -hex 32` and prefix with 0x, or `cast wallet new`. Never reuse a personal wallet key, never commit it, and cap its balance. Use SIGNER_MODE=turnkey or lit in production instead.',
    blocksFeatures: ['localSigner'],
    validate: exactHexLength(32),
  }),
  def({
    key: 'SIGNER_MAX_USDC_PER_SESSION',
    group: 'signer',
    configPath: 'signer.maxUsdcPerSession',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 1000,
    description:
      'Cumulative USDC a single signer session may authorize. Caps blast radius of a signer compromise.',
    example: '1000',
    howToObtain:
      'A risk decision. Set it to the largest loss you are willing to absorb from one session.',
    blocksFeatures: [],
    validate: numberRange(1, 10_000_000),
  }),
  def({
    key: 'TURNKEY_API_PUBLIC_KEY',
    group: 'signer',
    configPath: 'signer.turnkeyApiPublicKey',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    description: 'Turnkey API public key identifying the MPC API user that signs authorizations.',
    example: '<your-turnkey-api-public-key>',
    howToObtain:
      '1. Create an organization at https://app.turnkey.com. 2. Create an API user. 3. Generate an API key pair; copy the public half here and the private half into TURNKEY_API_PRIVATE_KEY.',
    docsUrl: 'https://docs.turnkey.com/getting-started/quickstart',
    blocksFeatures: ['mpcSigner'],
  }),
  def({
    key: 'TURNKEY_API_PRIVATE_KEY',
    group: 'signer',
    configPath: 'signer.turnkeyApiPrivateKey',
    type: 'string',
    required: OPTIONAL,
    secret: true,
    description:
      'Turnkey API private key. Authenticates AnyX to Turnkey; it is not the signing key itself.',
    example: '<your-turnkey-api-private-key>',
    howToObtain:
      'Generated alongside TURNKEY_API_PUBLIC_KEY at https://app.turnkey.com and shown once. Store it in your secret manager.',
    docsUrl: 'https://docs.turnkey.com/getting-started/quickstart',
    blocksFeatures: ['mpcSigner'],
  }),
  def({
    key: 'TURNKEY_ORGANIZATION_ID',
    group: 'signer',
    configPath: 'signer.turnkeyOrganizationId',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    description: 'Turnkey organization that owns the signing wallet.',
    example: '<your-turnkey-organization-id>',
    howToObtain:
      'Shown in the Turnkey dashboard at https://app.turnkey.com under Organization settings.',
    blocksFeatures: ['mpcSigner'],
  }),
  def({
    key: 'TURNKEY_PRIVATE_KEY_ID',
    group: 'signer',
    configPath: 'signer.turnkeyPrivateKeyId',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    description: 'Identifier of the Turnkey-held key that signs EIP-3009 authorizations.',
    example: '<your-turnkey-private-key-id>',
    howToObtain:
      'Create a wallet or private key in the Turnkey dashboard (https://app.turnkey.com) and copy its id. Attach a policy that only permits EIP-712 TransferWithAuthorization signing.',
    blocksFeatures: ['mpcSigner'],
  }),
  def({
    key: 'LIT_PROTOCOL_API_KEY',
    group: 'signer',
    configPath: 'signer.litApiKey',
    type: 'string',
    required: OPTIONAL,
    secret: true,
    description: 'Lit Protocol API key, used when SIGNER_MODE=lit for threshold signing.',
    example: '<your-lit-protocol-api-key>',
    howToObtain:
      '1. Register at https://developer.litprotocol.com. 2. Create a project and copy its API key. 3. Mint a PKP and record its public key in LIT_PKP_PUBLIC_KEY.',
    docsUrl: 'https://developer.litprotocol.com/sdk/installation',
    blocksFeatures: ['mpcSigner'],
  }),
  def({
    key: 'LIT_PKP_PUBLIC_KEY',
    group: 'signer',
    configPath: 'signer.litPkpPublicKey',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    description: 'Public key of the Lit PKP whose threshold shares produce the signature.',
    example: '<your-lit-pkp-public-key>',
    howToObtain:
      'Returned when you mint a PKP with the Lit SDK; also listed in the Lit developer dashboard.',
    blocksFeatures: ['mpcSigner'],
  }),
  def({
    key: 'LIT_NETWORK',
    group: 'signer',
    configPath: 'signer.litNetwork',
    type: 'enum',
    enumValues: ['datil-dev', 'datil-test', 'datil'],
    required: OPTIONAL,
    secret: false,
    default: 'datil-dev',
    description: 'Lit Protocol network to connect to. Use `datil` for production.',
    example: 'datil-dev',
    howToObtain:
      'Choose the network named in the Lit docs for your stage: datil-dev, datil-test, or datil.',
    blocksFeatures: [],
  }),

  // ------------------------------------------------------------------- fees
  def({
    key: 'FEE_BPS',
    group: 'fees',
    configPath: 'fees.feeBps',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 20,
    description:
      'Default AnyX spread in basis points applied on top of the required USDC. 20 = 0.20%.',
    example: '20',
    howToObtain: 'A pricing decision. The whitepaper models a 0.20% blended spread.',
    blocksFeatures: [],
    validate: numberRange(0, 100),
  }),
  def({
    key: 'MIN_FEE_USDC',
    group: 'fees',
    configPath: 'fees.minFeeUsdc',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 0.001,
    description: 'Fee floor in USDC, so micro-payments still cover their own routing cost.',
    example: '0.001',
    howToObtain: 'A pricing decision, not a credential.',
    blocksFeatures: [],
    validate: numberRange(0, 100),
  }),
  def({
    key: 'FEE_BPS_STABLE',
    group: 'fees',
    configPath: 'fees.feeBpsStable',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 5,
    description:
      'Spread for stablecoin pairs such as USDT to USDC, where AMM slippage is near zero.',
    example: '5',
    howToObtain: 'A pricing decision. 5 bps matches the published USDT to USDC rate.',
    blocksFeatures: [],
    validate: numberRange(0, 100),
  }),
  def({
    key: 'FEE_BPS_ETH',
    group: 'fees',
    configPath: 'fees.feeBpsEth',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 20,
    description: 'Spread for ETH and WETH routed to USDC.',
    example: '20',
    howToObtain: 'A pricing decision, not a credential.',
    blocksFeatures: [],
    validate: numberRange(0, 100),
  }),
  def({
    key: 'FEE_BPS_BTC',
    group: 'fees',
    configPath: 'fees.feeBpsBtc',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 50,
    description:
      'Spread for BTC-denominated inflows (Lightning, cbBTC, WBTC), which carry more rate risk.',
    example: '50',
    howToObtain: 'A pricing decision, not a credential.',
    blocksFeatures: [],
    validate: numberRange(0, 100),
  }),
  def({
    key: 'FEE_BPS_CROSSCHAIN',
    group: 'fees',
    configPath: 'fees.feeBpsCrosschain',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 30,
    description:
      'Spread for payments that require a bridge hop or float advance before settlement.',
    example: '30',
    howToObtain: 'A pricing decision, not a credential.',
    blocksFeatures: [],
    validate: numberRange(0, 100),
  }),
  def({
    key: 'MAX_FEE_BPS',
    group: 'fees',
    configPath: 'fees.maxFeeBps',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 100,
    description:
      'Hard ceiling enforced by the API and the router contract. Rejects any misconfigured spread.',
    example: '100',
    howToObtain: 'A policy decision. The router contract caps this at 100 bps (1%).',
    blocksFeatures: [],
    validate: numberRange(1, 100),
  }),

  // ---------------------------------------------------------------- storage
  def({
    key: 'DATABASE_URL',
    group: 'storage',
    configPath: 'storage.databaseUrl',
    type: 'string',
    required: ALL,
    secret: true,
    description:
      'PostgreSQL connection string for quotes, payments, receipts, API keys, and invoices.',
    example: 'postgresql://<user>:<password>@<host>:5432/anyx',
    howToObtain:
      'Local with Docker: `docker compose up -d postgres` then use postgresql://anyx:anyx@localhost:5432/anyx. Without Docker: create a free database at https://neon.tech or https://supabase.com and copy the connection string (append ?sslmode=require for hosted providers).',
    blocksFeatures: ['persistence', 'adminApi'],
  }),
  def({
    key: 'DATABASE_POOL_MAX',
    group: 'storage',
    configPath: 'storage.databasePoolMax',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 10,
    description: 'Maximum PostgreSQL connections per API instance.',
    example: '10',
    howToObtain: "A tuning decision. Keep the total across instances under your provider's limit.",
    blocksFeatures: [],
    validate: numberRange(1, 200),
  }),
  def({
    key: 'REDIS_URL',
    group: 'storage',
    configPath: 'storage.redisUrl',
    type: 'string',
    required: ALL,
    secret: true,
    description: 'Redis connection string for quote caching, rate limiting, and nonce tracking.',
    example: 'redis://<host>:6379',
    howToObtain:
      'Local with Docker: `docker compose up -d redis` then use redis://localhost:6379. Without Docker: create a free database at https://upstash.com and copy the rediss:// URL.',
    blocksFeatures: ['quoteCache', 'rateLimiting'],
  }),
  def({
    key: 'QUOTE_CACHE_TTL_SECONDS',
    group: 'storage',
    configPath: 'storage.quoteCacheTtlSeconds',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 30,
    description: 'How long a DEX quote stays valid. Also the expiry written onto issued quotes.',
    example: '30',
    howToObtain: 'A policy decision. The PRD specifies a 30 second quote validity window.',
    blocksFeatures: [],
    validate: numberRange(5, 300),
  }),

  // -------------------------------------------------------------------- api
  def({
    key: 'PORT',
    group: 'api',
    configPath: 'api.port',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 3000,
    description: 'Port the Hono API server binds to.',
    example: '3000',
    howToObtain: 'Any free local port. No third party involved.',
    blocksFeatures: [],
    validate: numberRange(1, 65535),
  }),
  def({
    key: 'API_BASE_URL',
    group: 'api',
    configPath: 'api.baseUrl',
    type: 'url',
    required: OPTIONAL,
    secret: false,
    default: 'http://localhost:3000',
    description:
      'Public base URL of this API deployment. Used in receipts, docs links, and SDK defaults.',
    example: 'http://localhost:3000',
    howToObtain: 'Your own deployment URL. Locally, http://localhost:3000.',
    blocksFeatures: [],
    validate: oneOfProtocols('http', 'https'),
  }),
  def({
    key: 'API_SECRET',
    group: 'api',
    configPath: 'api.secret',
    type: 'string',
    required: FROM_STAGING,
    secret: true,
    description:
      'Bearer secret guarding admin endpoints: key issuance, partner settlement, float operations.',
    example: '<generate-a-32-byte-random-string>',
    howToObtain:
      'Generate your own: `openssl rand -hex 32`. Store it in your secret manager and rotate it if it is ever printed to a log.',
    blocksFeatures: ['adminApi'],
  }),
  def({
    key: 'ANYX_API_KEY',
    group: 'api',
    configPath: 'api.anyxApiKey',
    type: 'string',
    required: OPTIONAL,
    secret: true,
    description:
      'AnyX API key used by the SDK, integration packages, and end-to-end tests when calling a hosted API.',
    example: '<your-anyx-api-key>',
    howToObtain:
      'Self-hosted: issue one through the admin endpoint POST /v1/keys using API_SECRET. Hosted: register through the developer portal of the deployment you are calling.',
    blocksFeatures: [],
  }),
  def({
    key: 'CORS_ALLOWED_ORIGINS',
    group: 'api',
    configPath: 'api.corsAllowedOrigins',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    default: '*',
    description: 'Comma-separated allowed origins. Narrow this before exposing the API publicly.',
    example: 'https://app.example.com,https://docs.example.com',
    howToObtain: 'A policy decision. Use * only in development.',
    blocksFeatures: [],
  }),
  def({
    key: 'RATE_LIMIT_FREE_RPM',
    group: 'api',
    configPath: 'api.rateLimitFreeRpm',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 100,
    description: 'Requests per minute allowed on the free tier.',
    example: '100',
    howToObtain: 'A policy decision, not a credential.',
    blocksFeatures: [],
    validate: numberRange(1, 100000),
  }),
  def({
    key: 'RATE_LIMIT_PRO_RPM',
    group: 'api',
    configPath: 'api.rateLimitProRpm',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 1000,
    description: 'Requests per minute allowed on the Pro tier.',
    example: '1000',
    howToObtain: 'A policy decision, not a credential.',
    blocksFeatures: [],
    validate: numberRange(1, 1000000),
  }),

  // -------------------------------------------------------------- contracts
  def({
    key: 'USDC_BASE',
    group: 'contracts',
    configPath: 'contracts.usdcBase',
    type: 'address',
    required: ALL,
    secret: false,
    default: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    description: 'Native USDC on Base. The settlement asset and the EIP-3009 verifying contract.',
    example: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    howToObtain:
      'Already set to the canonical Circle-issued USDC on Base. Verify against https://developers.circle.com/stablecoins/usdc-contract-addresses before changing it.',
    blocksFeatures: [],
  }),
  def({
    key: 'PERMIT2_ADDRESS',
    group: 'contracts',
    configPath: 'contracts.permit2',
    type: 'address',
    required: OPTIONAL,
    secret: false,
    default: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
    description: 'Uniswap Permit2, used for gasless input-token approvals into the router.',
    example: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
    howToObtain:
      'Permit2 is deployed at the same address on every supported chain. Leave the default.',
    blocksFeatures: [],
  }),
  def({
    key: 'ANYX_ROUTER',
    group: 'contracts',
    configPath: 'contracts.anyxRouter',
    type: 'address',
    required: OPTIONAL,
    secret: false,
    description:
      'Deployed AnyXRouter address. Unset until contracts are deployed for this environment.',
    example: '0x<40-hex-characters>',
    howToObtain:
      'Produced by the contract deployment: `forge script script/Deploy.s.sol --rpc-url $RPC_URL_BASE_SEPOLIA --broadcast --verify`. Copy the address from deployments/<network>.json. Until it is set, AnyX settles from the pre-funded USDC float instead of swapping on-chain.',
    blocksFeatures: ['onchainSwap'],
  }),
  def({
    key: 'FEE_COLLECTOR',
    group: 'contracts',
    configPath: 'contracts.feeCollector',
    type: 'address',
    required: OPTIONAL,
    secret: false,
    description: 'Address that receives the AnyX spread. Should be a multisig in production.',
    example: '0x<40-hex-characters>',
    howToObtain:
      'Either the FeeCollector contract emitted by the deploy script, or a Safe you create at https://app.safe.global. Revenue accrues here, so prefer a multisig over an EOA.',
    blocksFeatures: [],
  }),
  def({
    key: 'RESERVE_POOL',
    group: 'contracts',
    configPath: 'contracts.reservePool',
    type: 'address',
    required: OPTIONAL,
    secret: false,
    description:
      'ReservePool contract holding the USDC float that fronts cross-chain and Lightning payments.',
    example: '0x<40-hex-characters>',
    howToObtain:
      'Deployed by the contract deploy script in Phase 3. After deployment, fund it with USDC from the float funding wallet.',
    blocksFeatures: ['reserveFloat', 'floatSettlement'],
  }),
  def({
    key: 'BASESCAN_API_KEY',
    group: 'contracts',
    configPath: 'contracts.basescanApiKey',
    type: 'string',
    required: OPTIONAL,
    secret: true,
    description: 'Basescan key used by Foundry to verify deployed contract source.',
    example: '<your-basescan-api-key>',
    howToObtain:
      '1. Create an account at https://basescan.org/register. 2. Open API Keys. 3. Add a key and copy it. Free tier is sufficient for verification.',
    blocksFeatures: ['contractVerification'],
  }),

  // ----------------------------------------------------------------- bridge
  def({
    key: 'CCTP_ATTESTER_URL',
    group: 'bridge',
    configPath: 'bridge.cctpAttesterUrl',
    type: 'url',
    required: OPTIONAL,
    secret: false,
    default: 'https://iris-api.circle.com',
    description:
      'Circle Iris attestation service polled between a CCTP burn and the destination mint.',
    example: 'https://iris-api.circle.com',
    howToObtain:
      'Public and keyless. Use https://iris-api.circle.com for mainnet and https://iris-api-sandbox.circle.com for testnets.',
    docsUrl: 'https://developers.circle.com/stablecoins/docs/cctp-getting-started',
    blocksFeatures: ['crosschainCctp'],
    validate: oneOfProtocols('http', 'https'),
  }),
  def({
    key: 'STARGATE_ROUTER_ADDRESS',
    group: 'bridge',
    configPath: 'bridge.stargateRouter',
    type: 'address',
    required: OPTIONAL,
    secret: false,
    description: 'Stargate router used as the CCTP fallback for USDT and ETH bridging.',
    example: '0x<40-hex-characters>',
    howToObtain:
      'Look up the router for your source chain in the Stargate deployment list at https://stargateprotocol.gitbook.io/stargate/developers/contract-addresses/mainnet and paste the address.',
    blocksFeatures: ['stargateBridge'],
  }),
  def({
    key: 'FLOAT_POOL_TARGET_USDC',
    group: 'bridge',
    configPath: 'bridge.floatPoolTargetUsdc',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 10000,
    description:
      'Target USDC float on Base. Drives replenishment alerts and float utilisation limits.',
    example: '10000',
    howToObtain:
      'A capital decision. The strategy note suggests a 10,000 to 50,000 USDC float for the Lightning and cross-chain paths.',
    blocksFeatures: [],
    validate: numberRange(0, 100_000_000),
  }),
  def({
    key: 'FLOAT_FUNDING_WALLET',
    group: 'bridge',
    configPath: 'bridge.floatFundingWallet',
    type: 'address',
    required: OPTIONAL,
    secret: false,
    description:
      'Treasury address that funds and withdraws the reserve float. Only this address may top the pool up.',
    example: '0x<40-hex-characters>',
    howToObtain:
      'Create a Safe multisig at https://app.safe.global on Base, fund it with USDC, and paste its address. This is a human step: no code path can create the float for you.',
    blocksFeatures: ['reserveFloat'],
  }),
  def({
    key: 'BRIDGE_POLL_INTERVAL_MS',
    group: 'bridge',
    configPath: 'bridge.pollIntervalMs',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 5000,
    description: 'How often the bridge monitor polls Circle Iris for an attestation.',
    example: '5000',
    howToObtain: 'A tuning decision, not a credential.',
    blocksFeatures: [],
    validate: numberRange(500, 120000),
  }),
  def({
    key: 'BRIDGE_MAX_WAIT_SECONDS',
    group: 'bridge',
    configPath: 'bridge.maxWaitSeconds',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 900,
    description:
      'Give up on a bridge leg after this long and fall back to the float or refund the payer.',
    example: '900',
    howToObtain: 'A policy decision. CCTP typically settles in 2 to 10 minutes.',
    blocksFeatures: [],
    validate: numberRange(30, 7200),
  }),

  // -------------------------------------------------------------- lightning
  def({
    key: 'LND_GRPC_HOST',
    group: 'lightning',
    configPath: 'lightning.lndGrpcHost',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    description: 'host:port of the LND gRPC interface that issues and watches Lightning invoices.',
    example: '<your-lnd-host>:10009',
    howToObtain:
      'Run your own LND node (https://github.com/lightningnetwork/lnd) on a VPS, or use a hosted node such as Voltage (https://voltage.cloud). Copy the gRPC host and port; port 10009 is the LND default.',
    blocksFeatures: ['lightning'],
  }),
  def({
    key: 'LND_TLS_CERT_PATH',
    group: 'lightning',
    configPath: 'lightning.lndTlsCertPath',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    description: 'Filesystem path to the LND TLS certificate used to establish the gRPC channel.',
    example: '/secrets/lnd/tls.cert',
    howToObtain:
      'Copy tls.cert from your LND data directory (~/.lnd/tls.cert) onto the API host and point this at it. Mount it as a read-only secret; do not commit it.',
    blocksFeatures: ['lightning'],
  }),
  def({
    key: 'LND_MACAROON_PATH',
    group: 'lightning',
    configPath: 'lightning.lndMacaroonPath',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    description: 'Filesystem path to the LND macaroon that grants invoice permissions.',
    example: '/secrets/lnd/invoice.macaroon',
    howToObtain:
      'Bake a least-privilege macaroon with `lncli bakemacaroon invoices:read invoices:write` rather than reusing admin.macaroon, copy it to the API host, and point this at it. The macaroon file is a credential: mount it read-only and keep it out of git.',
    blocksFeatures: ['lightning'],
  }),
  def({
    key: 'LIGHTNING_INVOICE_EXPIRY_SECONDS',
    group: 'lightning',
    configPath: 'lightning.invoiceExpirySeconds',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 300,
    description:
      'Lightning invoice expiry. Keep it at or below the x402 challenge maxTimeoutSeconds.',
    example: '300',
    howToObtain: 'A policy decision. 300 seconds matches the x402 default challenge window.',
    blocksFeatures: [],
    validate: numberRange(30, 3600),
  }),
  def({
    key: 'BTC_RATE_BUFFER_BPS',
    group: 'lightning',
    configPath: 'lightning.btcRateBufferBps',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 50,
    description:
      'Conservative buffer added to the BTC/USD rate so invoice sizing survives rate movement.',
    example: '50',
    howToObtain: "A risk decision. 50 bps (0.5%) matches the roadmap's suggested buffer.",
    blocksFeatures: [],
    validate: numberRange(0, 1000),
  }),

  // ---------------------------------------------------------------- billing
  def({
    key: 'STRIPE_SECRET_KEY',
    group: 'billing',
    configPath: 'billing.stripeSecretKey',
    type: 'string',
    required: OPTIONAL,
    secret: true,
    description: 'Stripe secret key used to create Checkout sessions and customer portal links.',
    example: '<your-stripe-secret-key>',
    howToObtain:
      '1. Create an account at https://dashboard.stripe.com/register. 2. Open Developers then API keys. 3. Copy the secret key. Use a test-mode key outside production and never the publishable key.',
    docsUrl: 'https://docs.stripe.com/keys',
    blocksFeatures: ['stripeBilling'],
  }),
  def({
    key: 'STRIPE_PRO_PRICE_ID',
    group: 'billing',
    configPath: 'billing.stripeProPriceId',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    description: 'Stripe Price id for the Pro subscription that Checkout sessions reference.',
    example: '<your-stripe-price-id>',
    howToObtain:
      '1. In the Stripe dashboard create a Product for the AnyX Pro plan. 2. Add a recurring monthly price. 3. Copy the price id from the price detail page.',
    docsUrl: 'https://docs.stripe.com/products-prices/how-products-and-prices-work',
    blocksFeatures: ['stripeBilling'],
  }),
  def({
    key: 'STRIPE_WEBHOOK_SECRET',
    group: 'billing',
    configPath: 'billing.stripeWebhookSecret',
    type: 'string',
    required: OPTIONAL,
    secret: true,
    description: 'Signing secret used to verify Stripe webhook payloads before acting on them.',
    example: '<your-stripe-webhook-signing-secret>',
    howToObtain:
      '1. In the Stripe dashboard add a webhook endpoint pointing at https://<your-api-host>/webhooks/stripe. 2. Subscribe to checkout.session.completed, customer.subscription.deleted, and invoice.payment_failed. 3. Copy the signing secret. Locally, `stripe listen --forward-to localhost:3000/webhooks/stripe` prints one.',
    docsUrl: 'https://docs.stripe.com/webhooks',
    blocksFeatures: ['stripeBilling'],
  }),
  def({
    key: 'STRIPE_PORTAL_RETURN_URL',
    group: 'billing',
    configPath: 'billing.stripePortalReturnUrl',
    type: 'url',
    required: OPTIONAL,
    secret: false,
    description: 'Where Stripe returns the user after they manage their subscription.',
    example: 'http://localhost:3000/portal',
    howToObtain: 'Any URL you control, typically the developer portal page of your dashboard.',
    blocksFeatures: [],
    validate: oneOfProtocols('http', 'https'),
  }),

  // ----------------------------------------------------------------- deploy
  def({
    key: 'FLY_API_TOKEN',
    group: 'deploy',
    configPath: 'deploy.flyApiToken',
    type: 'string',
    required: OPTIONAL,
    secret: true,
    description: 'Fly.io deploy token used by CI to ship the API and Lightning services.',
    example: '<your-fly-deploy-token>',
    howToObtain:
      '1. Install flyctl from https://fly.io/docs/flyctl/install. 2. Run `fly tokens create deploy` (scoped to one app) and copy the token. 3. Store it as the GitHub Actions secret FLY_API_TOKEN. Never place it in .env files that ship with the repo.',
    docsUrl: 'https://fly.io/docs/launch/deploy',
    blocksFeatures: ['apiDeploy'],
  }),
  def({
    key: 'FLY_APP_API',
    group: 'deploy',
    configPath: 'deploy.flyAppApi',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    default: 'anyx-api',
    description: 'Fly.io app name for the REST API.',
    example: 'anyx-api',
    howToObtain: 'Created by `fly launch`; app names are globally unique, so pick a name you own.',
    blocksFeatures: [],
  }),
  def({
    key: 'FLY_APP_LIGHTNING',
    group: 'deploy',
    configPath: 'deploy.flyAppLightning',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    default: 'anyx-lightning',
    description: 'Fly.io app name for the Lightning service.',
    example: 'anyx-lightning',
    howToObtain:
      'Created by `fly launch` in apps/lightning. Only needed once the Lightning path is enabled.',
    blocksFeatures: [],
  }),
  def({
    key: 'HEALTHCHECK_URL',
    group: 'deploy',
    configPath: 'deploy.healthcheckUrl',
    type: 'url',
    required: OPTIONAL,
    secret: false,
    default: 'http://localhost:3000/health',
    description: 'URL polled after deploy to confirm the release is serving traffic.',
    example: 'http://localhost:3000/health',
    howToObtain: 'The /health route of the deployment you are releasing.',
    blocksFeatures: [],
    validate: oneOfProtocols('http', 'https'),
  }),
  def({
    key: 'NPM_TOKEN',
    group: 'deploy',
    configPath: 'deploy.npmToken',
    type: 'string',
    required: OPTIONAL,
    secret: true,
    description: 'npm automation token used to publish @anyx/sdk and the integration packages.',
    example: '<your-npm-automation-token>',
    howToObtain:
      '1. Sign in at https://www.npmjs.com. 2. Open Access Tokens and create a Granular Access or Automation token scoped to the @anyx org. 3. Store it as the GitHub Actions secret NPM_TOKEN.',
    docsUrl: 'https://docs.npmjs.com/creating-and-viewing-access-tokens',
    blocksFeatures: ['sdkPublish'],
  }),

  // ----------------------------------------------------------- orchestrator
  def({
    key: 'ORCHESTRATOR_AGENT_CMD',
    group: 'orchestrator',
    configPath: 'orchestrator.agentCommand',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    default: 'cursor-agent',
    description: 'Executable the orchestrator invokes to run one specialist agent task locally.',
    example: 'cursor-agent',
    howToObtain:
      'The command of whatever agent runner you use. It must accept a prompt on stdin and exit non-zero on failure.',
    blocksFeatures: [],
  }),
  def({
    key: 'ORCHESTRATOR_AGENT_ENDPOINT',
    group: 'orchestrator',
    configPath: 'orchestrator.agentEndpoint',
    type: 'url',
    required: OPTIONAL,
    secret: false,
    description:
      'HTTP endpoint for a remote agent executor. When unset, tasks run through the local command.',
    example: 'https://agents.your-domain.example/dispatch',
    howToObtain:
      'The dispatch URL of your own agent-runner service. Leave unset to run agents locally.',
    blocksFeatures: ['orchestratorRemoteExecutor'],
    validate: oneOfProtocols('http', 'https'),
  }),
  def({
    key: 'ORCHESTRATOR_MAX_FIX_ATTEMPTS',
    group: 'orchestrator',
    configPath: 'orchestrator.maxFixAttempts',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 3,
    description: 'Auto-fix attempts per failing task before the orchestrator escalates to a human.',
    example: '3',
    howToObtain: 'A policy decision, not a credential.',
    blocksFeatures: [],
    validate: numberRange(0, 10),
  }),
  def({
    key: 'ORCHESTRATOR_CONCURRENCY',
    group: 'orchestrator',
    configPath: 'orchestrator.concurrency',
    type: 'number',
    required: OPTIONAL,
    secret: false,
    default: 3,
    description: 'How many specialist agents may run at once against the same working tree.',
    example: '3',
    howToObtain:
      'A tuning decision. Keep it low enough that agents own disjoint file scopes and avoid git contention.',
    blocksFeatures: [],
    validate: numberRange(1, 32),
  }),
  def({
    key: 'ORCHESTRATOR_AUTO_APPROVE_PRODUCTION',
    group: 'orchestrator',
    configPath: 'orchestrator.autoApproveProduction',
    type: 'boolean',
    required: OPTIONAL,
    secret: false,
    default: false,
    description:
      'When false (the default), a human must approve every production promotion. Only the operator should change this.',
    example: 'false',
    howToObtain:
      'A governance decision. Leave it false until contracts are audited and the float is funded.',
    blocksFeatures: ['orchestratorProductionAutoApprove'],
  }),
  def({
    key: 'ORCHESTRATOR_STATE_DIR',
    group: 'orchestrator',
    configPath: 'orchestrator.stateDir',
    type: 'string',
    required: OPTIONAL,
    secret: false,
    default: '.anyx/orchestrator',
    description: 'Directory holding orchestrator run state, task logs, and bug reports.',
    example: '.anyx/orchestrator',
    howToObtain: 'Any writable path. Keep it out of version control.',
    blocksFeatures: [],
  }),
];

export const REQUIREMENT_RULES: readonly RequirementRule[] = [
  {
    id: 'signer',
    title: 'A signer must be configured (local hot key or MPC)',
    anyOf: ['PRIVATE_KEY', 'TURNKEY_API_PRIVATE_KEY', 'LIT_PROTOCOL_API_KEY'],
    requiredIn: ['dev', 'staging', 'production'],
    howToObtain:
      'Set SIGNER_MODE=local and PRIVATE_KEY for development (generate a throwaway key with `openssl rand -hex 32`), or SIGNER_MODE=turnkey with the TURNKEY_* keys from https://app.turnkey.com, or SIGNER_MODE=lit with LIT_PROTOCOL_API_KEY from https://developer.litprotocol.com. Without one of these, AnyX cannot sign EIP-3009 authorizations and no payment can settle.',
    blocksFeatures: ['localSigner', 'mpcSigner'],
  },
  {
    id: 'dex-quote-source',
    title: 'At least one DEX aggregator key is needed to quote EVM swaps',
    anyOf: ['ONEINCH_API_KEY', 'ZEROX_API_KEY'],
    requiredIn: ['staging', 'production'],
    howToObtain:
      'Create a 1inch key at https://portal.1inch.dev or a 0x key at https://dashboard.0x.org. Configure both to get automatic failover between aggregators.',
    blocksFeatures: ['evmQuotes'],
  },
  {
    id: 'production-signer-mpc',
    title: 'Production signing should be MPC-backed, not a local hot key',
    anyOf: ['TURNKEY_API_PRIVATE_KEY', 'LIT_PROTOCOL_API_KEY'],
    requiredIn: ['production'],
    howToObtain:
      'Provision a Turnkey organization (https://app.turnkey.com) or a Lit PKP (https://developer.litprotocol.com), set SIGNER_MODE accordingly, and remove PRIVATE_KEY from the production environment. A single hot key that can authorize USDC transfers is the highest-severity item in the threat model.',
    blocksFeatures: ['mpcSigner'],
  },
];

export const REGISTRY_BY_KEY: Readonly<Record<string, ConfigKeyDefinition>> = Object.freeze(
  Object.fromEntries(CONFIG_REGISTRY.map((entry) => [entry.key, entry])),
);

export const REGISTRY_BY_CONFIG_PATH: Readonly<Record<string, ConfigKeyDefinition>> = Object.freeze(
  Object.fromEntries(CONFIG_REGISTRY.map((entry) => [entry.configPath, entry])),
);

export function keysForGroup(group: ConfigGroup): readonly ConfigKeyDefinition[] {
  return CONFIG_REGISTRY.filter((entry) => entry.group === group);
}

export function isRequired(definition: ConfigKeyDefinition, env: ConfigEnvironment): boolean {
  return definition.required[env];
}

export function findKey(key: string): ConfigKeyDefinition | undefined {
  const exact = REGISTRY_BY_KEY[key];
  if (exact) return exact;
  const upper = key.toUpperCase();
  return CONFIG_REGISTRY.find(
    (entry) => entry.key === upper || entry.configPath.toLowerCase() === key.toLowerCase(),
  );
}
