import type { TaskDefinition } from './types.ts';

export const PHASE_0_TASKS: readonly TaskDefinition[] = [
  {
    id: '0.1-monorepo',
    title: 'Initialize the Turborepo monorepo',
    phase: 0,
    agentId: 'devops',
    summary:
      'Initialize a Bun-workspaces Turborepo named "anyx" with packages @anyx/core, @anyx/sdk, @anyx/contracts, @anyx/db and apps api (Hono) and dashboard (Next.js 14 App Router). Configure turbo.json with build, test, lint and dev pipelines, a strict root tsconfig.json, and Biome for lint and format. Every package gets name, version 0.1.0 and its workspace dependencies.',
    dependsOn: [],
    ownedPaths: [
      'package.json',
      'turbo.json',
      'tsconfig.json',
      'biome.json',
      'packages/*/package.json',
      'apps/*/package.json',
    ],
    acceptanceCriteria: [
      { kind: 'file-exists', description: 'Root package.json declares workspaces', path: 'package.json' },
      { kind: 'file-contains', description: 'Workspaces include packages and apps', path: 'package.json', pattern: 'workspaces' },
      { kind: 'file-exists', description: 'turbo.json defines the pipelines', path: 'turbo.json' },
      { kind: 'file-contains', description: 'TypeScript strict mode is on', path: 'tsconfig.json', pattern: '"strict"\\s*:\\s*true' },
      { kind: 'command', description: 'The workspace builds from the root', command: 'bun run build' },
    ],
    verifyCommands: [
      { command: 'bun run typecheck' },
      { command: 'bun run lint', optional: true },
    ],
    requiredConfigKeys: [],
    requiredManualGates: [],
    status: 'pending',
    priority: 0,
    estimatedComplexity: 'medium',
    references: ['docs/reference/agent-build-roadmap.md#task-01--initialize-turborepo-monorepo'],
  },
  {
    id: '0.2-db-schema',
    title: 'Drizzle schema and migrations',
    phase: 0,
    agentId: 'data',
    summary:
      'Set up Drizzle ORM with PostgreSQL in packages/db. Define four tables: quotes, payments, api_keys and lightning_invoices, exactly as specified in the roadmap including enums and foreign keys. Amounts are varchar base-unit strings. api_keys stores only a SHA-256 key_hash, indexed. Wire drizzle-kit for generate and migrate and export every row and insert type from @anyx/db.',
    dependsOn: ['0.1-monorepo'],
    ownedPaths: ['packages/db/**'],
    acceptanceCriteria: [
      { kind: 'file-exists', description: 'Schema module exists', path: 'packages/db/src/schema.ts' },
      { kind: 'file-contains', description: 'quotes table defined', path: 'packages/db/src/schema.ts', pattern: 'quotes' },
      { kind: 'file-contains', description: 'payments table defined', path: 'packages/db/src/schema.ts', pattern: 'payments' },
      { kind: 'file-contains', description: 'api_keys table defined', path: 'packages/db/src/schema.ts', pattern: 'api_?keys' },
      { kind: 'file-contains', description: 'lightning_invoices table defined', path: 'packages/db/src/schema.ts', pattern: 'lightning_?invoices' },
      { kind: 'command', description: 'Migrations generate', command: 'bun run db:generate' },
    ],
    verifyCommands: [
      { command: 'bun run db:generate' },
      { command: 'bun run typecheck' },
    ],
    requiredConfigKeys: ['DATABASE_URL'],
    requiredManualGates: ['postgres'],
    status: 'pending',
    priority: 1,
    estimatedComplexity: 'medium',
    references: ['docs/reference/agent-build-roadmap.md#task-02--database-schema'],
  },
  {
    id: '0.3-docker-compose',
    title: 'Docker Compose stack and setup script',
    phase: 0,
    agentId: 'devops',
    summary:
      'Create docker-compose.yml with PostgreSQL 16, Redis 7 and pgAdmin, each with a health check, plus docker-compose.prod.yml with only Postgres and Redis, named volumes and resource limits. The bootstrap script must tolerate a machine without Docker and point the operator at hosted Postgres and Redis instead.',
    dependsOn: ['0.1-monorepo'],
    ownedPaths: ['docker-compose.yml', 'docker-compose.prod.yml'],
    acceptanceCriteria: [
      { kind: 'file-exists', description: 'Compose file exists', path: 'docker-compose.yml' },
      { kind: 'file-contains', description: 'Postgres service defined', path: 'docker-compose.yml', pattern: 'postgres' },
      { kind: 'file-contains', description: 'Redis service defined', path: 'docker-compose.yml', pattern: 'redis' },
      { kind: 'file-contains', description: 'Health checks configured', path: 'docker-compose.yml', pattern: 'healthcheck' },
      { kind: 'command', description: 'Compose file is valid', command: 'docker compose config -q', requiresBinary: 'docker' },
    ],
    verifyCommands: [
      { command: 'docker compose config -q', requiresBinary: 'docker' },
      { command: 'bash -n scripts/setup.sh' },
    ],
    requiredConfigKeys: [],
    requiredManualGates: [],
    status: 'pending',
    priority: 2,
    estimatedComplexity: 'small',
    references: ['docs/reference/agent-build-roadmap.md#task-03--docker-compose'],
  },
];
