import type { TaskDefinition } from './types.ts';

export const PHASE_1_TASKS: readonly TaskDefinition[] = [
  {
    id: '1.1-token-registry',
    title: 'Typed token registry',
    phase: 1,
    agentId: 'swap-routing',
    summary:
      'Create packages/core/src/tokens.ts with a Token type (symbol, name, address or null for natives, chainId, decimals, coingeckoId, isNative, swapPath of direct/bridge/lightning) and populate it with the eleven launch tokens from the roadmap across Base (8453), Ethereum (1), Solana (101) and Lightning. Export TOKEN_REGISTRY, getToken, getSupportedTokens and isSupported.',
    dependsOn: ['0.1-monorepo'],
    ownedPaths: ['packages/core/src/tokens.ts'],
    acceptanceCriteria: [
      { kind: 'file-exists', description: 'Token registry module exists', path: 'packages/core/src/tokens.ts' },
      { kind: 'file-contains', description: 'TOKEN_REGISTRY is exported', path: 'packages/core/src/tokens.ts', pattern: 'export const TOKEN_REGISTRY' },
      { kind: 'file-contains', description: 'Base USDC address present', path: 'packages/core/src/tokens.ts', pattern: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' },
      { kind: 'file-contains', description: 'Lightning swap path modelled', path: 'packages/core/src/tokens.ts', pattern: 'lightning' },
    ],
    verifyCommands: [{ command: 'bun run typecheck' }],
    requiredConfigKeys: [],
    requiredManualGates: [],
    status: 'pending',
    priority: 10,
    estimatedComplexity: 'small',
    references: ['docs/reference/agent-build-roadmap.md#task-11--token-registry'],
  },
  {
    id: '1.2-quote-engine',
    title: 'DEX quote aggregation engine',
    phase: 1,
    agentId: 'swap-routing',
    summary:
      'Create packages/core/src/quote.ts. Implement get1inchQuote, get0xQuote, getBestQuote and getCachedQuote. Call both aggregators with Promise.allSettled, pick the higher amountOut, and apply the AnyX spread as inputAmount = usdcRequired / (1 - feeBps/10000). Validate inputs with zod, cache in Redis for 30s, log quotes to the database, fall back to a single aggregator when the other fails and throw QuoteError when both do.',
    dependsOn: ['1.1-token-registry', '0.2-db-schema'],
    ownedPaths: ['packages/core/src/quote.ts', 'packages/core/src/fees.ts'],
    acceptanceCriteria: [
      { kind: 'file-exists', description: 'Quote engine module exists', path: 'packages/core/src/quote.ts' },
      { kind: 'file-contains', description: 'getBestQuote exported', path: 'packages/core/src/quote.ts', pattern: 'export .*getBestQuote' },
      { kind: 'file-contains', description: 'Both aggregators queried in parallel', path: 'packages/core/src/quote.ts', pattern: 'allSettled' },
      { kind: 'command', description: 'Quote unit tests pass', command: 'bun test packages/core' },
    ],
    verifyCommands: [{ command: 'bun test packages/core' }, { command: 'bun run typecheck' }],
    requiredConfigKeys: ['ONEINCH_API_KEY', 'ZEROX_API_KEY', 'REDIS_URL'],
    requiredManualGates: ['oneinch', 'zerox', 'redis'],
    status: 'pending',
    priority: 11,
    estimatedComplexity: 'large',
    references: ['docs/reference/agent-build-roadmap.md#task-12--dex-quote-engine'],
  },
  {
    id: '1.3-x402-parser',
    title: 'x402 challenge parser and payment header builder',
    phase: 1,
    agentId: 'protocol',
    summary:
      'Create packages/core/src/x402.ts implementing fetch402Challenge, parsePaymentRequired, buildPaymentHeader and submitPayment. Validate the x402 v2 body with zod, accept either the base64 PAYMENT-REQUIRED header or a JSON body, select the Base USDC option (network eip155:8453) and throw when no compatible option exists.',
    dependsOn: ['1.1-token-registry'],
    ownedPaths: ['packages/core/src/x402.ts'],
    acceptanceCriteria: [
      { kind: 'file-exists', description: 'x402 client module exists', path: 'packages/core/src/x402.ts' },
      { kind: 'file-contains', description: 'Challenge parser exported', path: 'packages/core/src/x402.ts', pattern: 'parsePaymentRequired' },
      { kind: 'file-contains', description: 'Base network selected by CAIP-2 id', path: 'packages/core/src/x402.ts', pattern: 'eip155:8453' },
      { kind: 'command', description: 'x402 unit tests pass', command: 'bun test packages/core' },
    ],
    verifyCommands: [{ command: 'bun test packages/core' }, { command: 'bun run typecheck' }],
    requiredConfigKeys: [],
    requiredManualGates: [],
    status: 'pending',
    priority: 12,
    estimatedComplexity: 'medium',
    references: ['docs/reference/agent-build-roadmap.md#task-13--x402-challenge-parser'],
  },
  {
    id: '1.4-eip3009',
    title: 'EIP-3009 authorization builder and signer',
    phase: 1,
    agentId: 'protocol',
    summary:
      'Create packages/core/src/eip3009.ts with buildAuthorizationPayload, signAuthorization and verifyAuthorization using viem. Nonces are 32 cryptographically random bytes, validAfter is 0 and validBefore is now plus 300 seconds. Sign the EIP-712 TransferWithAuthorization struct against the USD Coin version 2 domain and split the signature into v, r and s.',
    dependsOn: ['1.3-x402-parser'],
    ownedPaths: ['packages/core/src/eip3009.ts'],
    acceptanceCriteria: [
      { kind: 'file-exists', description: 'EIP-3009 module exists', path: 'packages/core/src/eip3009.ts' },
      { kind: 'file-contains', description: 'Typed-data signing used', path: 'packages/core/src/eip3009.ts', pattern: 'signTypedData' },
      { kind: 'file-contains', description: 'TransferWithAuthorization type defined', path: 'packages/core/src/eip3009.ts', pattern: 'TransferWithAuthorization' },
      { kind: 'command', description: 'Signature round-trip tests pass', command: 'bun test packages/core' },
    ],
    verifyCommands: [{ command: 'bun test packages/core' }, { command: 'bun run typecheck' }],
    requiredConfigKeys: ['RPC_URL_BASE'],
    requiredManualGates: ['evm-rpc', 'hot-signer'],
    status: 'pending',
    priority: 13,
    estimatedComplexity: 'medium',
    references: ['docs/reference/agent-build-roadmap.md#task-14--eip-3009-authorization-builder'],
  },
  {
    id: '1.5-facilitator',
    title: 'Facilitator client with failover',
    phase: 1,
    agentId: 'protocol',
    summary:
      'Create packages/core/src/facilitator.ts with verifyPayment, settlePayment, getFacilitatorUrl and waitForSettlement. Health-check the primary facilitator with a 2 second timeout and fall back to FACILITATOR_FALLBACK_URL when it is unhealthy. Poll for settlement for at most 30 seconds at 2 second intervals using viem waitForTransactionReceipt.',
    dependsOn: ['1.4-eip3009'],
    ownedPaths: ['packages/core/src/facilitator.ts'],
    acceptanceCriteria: [
      { kind: 'file-exists', description: 'Facilitator client exists', path: 'packages/core/src/facilitator.ts' },
      { kind: 'file-contains', description: 'Settlement endpoint called', path: 'packages/core/src/facilitator.ts', pattern: 'settle' },
      { kind: 'file-contains', description: 'Fallback facilitator wired', path: 'packages/core/src/facilitator.ts', pattern: 'FACILITATOR_FALLBACK_URL|fallback' },
      { kind: 'command', description: 'Failover tests pass', command: 'bun test packages/core' },
    ],
    verifyCommands: [{ command: 'bun test packages/core' }, { command: 'bun run typecheck' }],
    requiredConfigKeys: ['FACILITATOR_URL'],
    requiredManualGates: ['facilitator'],
    status: 'pending',
    priority: 14,
    estimatedComplexity: 'medium',
    references: ['docs/reference/agent-build-roadmap.md#task-15--facilitator-client'],
  },
  {
    id: '1.6-api-server',
    title: 'Hono API server and routes',
    phase: 1,
    agentId: 'backend',
    summary:
      'Build apps/api/src/index.ts on Hono and Bun with CORS, X-Request-ID, request logging, Redis rate limiting and structured error handling. Implement GET /health, GET /v1/tokens, POST /v1/quote, POST /v1/pay, GET /v1/receipt/:id and the POST /v1/lightning/invoice stub. Errors always take the shape { error: { code, message, details? } } using the fixed error-code set.',
    dependsOn: ['1.2-quote-engine', '1.5-facilitator', '0.2-db-schema'],
    ownedPaths: ['apps/api/**'],
    acceptanceCriteria: [
      { kind: 'file-exists', description: 'Server entry exists', path: 'apps/api/src/index.ts' },
      { kind: 'file-contains', description: 'Health route implemented', path: 'apps/api/src/index.ts', pattern: '/health' },
      { kind: 'file-exists', description: 'Quote route implemented', path: 'apps/api/src/routes/quote.ts' },
      { kind: 'file-exists', description: 'Pay route implemented', path: 'apps/api/src/routes/pay.ts' },
      { kind: 'file-exists', description: 'Rate limit middleware present', path: 'apps/api/src/middleware/rateLimit.ts' },
      { kind: 'command', description: 'API tests pass', command: 'bun test apps/api' },
    ],
    verifyCommands: [{ command: 'bun test apps/api' }, { command: 'bun run typecheck' }],
    requiredConfigKeys: ['DATABASE_URL', 'REDIS_URL', 'FACILITATOR_URL'],
    requiredManualGates: ['postgres', 'redis', 'facilitator'],
    status: 'pending',
    priority: 15,
    estimatedComplexity: 'large',
    references: ['docs/reference/agent-build-roadmap.md#task-16--api-server-routes'],
  },
  {
    id: '1.7-sdk',
    title: '@anyx/sdk UPA class and fetch drop-in',
    phase: 1,
    agentId: 'sdk',
    summary:
      'Build packages/sdk with the UPA class: constructor taking UPAConfig, and methods fetch, quote, pay, getReceipt and getSupportedTokens. upa.fetch must pass non-402 responses straight through and, on a 402, quote then pay then retry with the X-PAYMENT header. Enforce maxSlippage and maxFeePercent client side and export all public types.',
    dependsOn: ['1.6-api-server'],
    ownedPaths: ['packages/sdk/**'],
    acceptanceCriteria: [
      { kind: 'file-exists', description: 'SDK entry point exists', path: 'packages/sdk/src/index.ts' },
      { kind: 'file-contains', description: 'UPA class exported', path: 'packages/sdk/src/index.ts', pattern: 'class UPA|export .*UPA' },
      { kind: 'file-exists', description: 'SDK README documents the drop-in', path: 'packages/sdk/README.md' },
      { kind: 'command', description: 'SDK tests pass', command: 'bun test packages/sdk' },
    ],
    verifyCommands: [{ command: 'bun test packages/sdk' }, { command: 'bun run typecheck' }],
    requiredConfigKeys: [],
    requiredManualGates: [],
    status: 'pending',
    priority: 16,
    estimatedComplexity: 'large',
    references: ['docs/reference/agent-build-roadmap.md#task-17--sdk-package'],
  },
  {
    id: '1.8-unit-tests',
    title: 'Core and SDK unit test suites',
    phase: 1,
    agentId: 'qa',
    summary:
      'Write unit tests for quote, x402, eip3009, facilitator and the SDK. Mock every upstream. Cover fee calculation at 20 bps, 1inch failure falling back to 0x, quote expiry, base64 header parsing, the missing-Base-USDC error, nonce uniqueness across 100 generations, signature round-trip, a five minute validBefore, facilitator failover on 503 and the 2 second timeout. Coverage target is 80% of packages/core.',
    dependsOn: ['1.2-quote-engine', '1.3-x402-parser', '1.4-eip3009', '1.5-facilitator', '1.7-sdk'],
    ownedPaths: ['packages/core/src/__tests__/**', 'packages/sdk/src/__tests__/**'],
    acceptanceCriteria: [
      { kind: 'file-exists', description: 'Quote tests exist', path: 'packages/core/src/__tests__/quote.test.ts' },
      { kind: 'file-exists', description: 'x402 tests exist', path: 'packages/core/src/__tests__/x402.test.ts' },
      { kind: 'file-exists', description: 'EIP-3009 tests exist', path: 'packages/core/src/__tests__/eip3009.test.ts' },
      { kind: 'file-exists', description: 'Facilitator tests exist', path: 'packages/core/src/__tests__/facilitator.test.ts' },
      { kind: 'command', description: 'Full suite passes', command: 'bun test' },
    ],
    verifyCommands: [{ command: 'bun test' }],
    requiredConfigKeys: [],
    requiredManualGates: [],
    status: 'pending',
    priority: 17,
    estimatedComplexity: 'medium',
    references: ['docs/reference/agent-build-roadmap.md#task-18--unit-tests'],
  },
];
